server {
    listen 80;
    listen [::]:80;
    server_name _;

    # EFF Certbot challenge for TLS renewal
    location /.well-known/acme-challenge/ {
      root /usr/share/nginx/certbot;
    }

    # Other content uses https
    location / {
        return 301 https://$host$request_uri;
    }

    # Allow http for specific content?
    location /someplace {
        root /usr/share/nginx/html;
        index index.html;
    }
}

# https
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name _;

    # SSL Certificate Paths, independent of hostname
    # Doesn't work: the certs are symlinks using relative paths.
    ssl_certificate     /etc/nginx/certs/fullchain.pem;
    ssl_certificate_key /etc/nginx/certs/privkey.pem;

    # ${DOMAIN} requires using a template file (default.conf.template)
    #ssl_certificate     /etc/letsencrypt/live/${DOMAIN}/fullchain.pem;
    #ssl_certificate_key /etc/letsencrypt/live/${DOMAIN}/privkey.pem;

    # Performance and Security (Move to snippets/ssl-params.conf)
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;

    # Security settings
    include /etc/nginx/snippets/security.conf;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }
}
