# 1. Hide Nginx Version (Prevents targeted exploits)
server_tokens off;

# 2. Prevent Clickjacking
# Ensure your site cannot be embedded in an iframe on other domains
add_header X-Frame-Options "SAMEORIGIN" always;

# 3. MIME Sniffing Protection
# Prevents browsers from "guessing" the asset type, forcing them to follow the Content-Type header
add_header X-Content-Type-Options "nosniff" always;

# 4. XSS Protection (For older browsers)
add_header X-XSS-Protection "1; mode=block" always;

# 5. Content Security Policy (Basic)
# Restricts where resources (JS/CSS) can be loaded from. 
# Adjust "self" if you use external CDNs like Google Fonts.
# 'Least Privilege' settings.
# - script-src 'self';  allow only Javascript files hosted on your server. Blocks inline scripts and eval().
add_header Content-Security-Policy "default-src 'self'; script-src 'self'; style-src 'self'; base-uri 'self'; img-src 'self' data:; font-src 'self';" always;

# This version is more permissive. 
# It allows browser to load resources from any domain as long 
# as its over a valid protocol (http, https, data).
# add_header Content-Security-Policy "default-src 'self' http: https: data: blob:" always;

# 6. Referrer Policy
# Controls how much path information is sent when a user clicks a link to another site
add_header Referrer-Policy "strict-origin-when-cross-origin" always;

# 7. HTTP Strict Transport Security (HSTS)
# Tells the browser to ONLY use HTTPS for this site for the next year. 
# WARNING: enable this ONLY if you have a working TLS cert!
#
#add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;
