# The "inventory" of hosts to configure.

[lab66]
# These are aliases in .ssh/config, instead of specifying details here.
lab066

[lab]
# All the Lab VMs.  Short aliases (lab066) defined in .ssh/config.
lab066.kasetsart.university
lab067.kasetsart.university
lab068.kasetsart.university
lab069.kasetsart.university
lab070.kasetsart.university
lab071.kasetsart.university
lab072.kasetsart.university
lab073.kasetsart.university
lab074.kasetsart.university
lab075.kasetsart.university
lab076.kasetsart.university
lab077.kasetsart.university
lab078.kasetsart.university
lab079.kasetsart.university
lab080.kasetsart.university

[lab66:vars]
# Specify Python interpretter to supress Ansible warning
# about auto-detected Python interpretter.
# Alternatively, you can specify it on each host individually.
ansible_python_interpreter=/usr/bin/python3.9

[lab:vars]
ansible_python_interpreter=/usr/bin/python3.9
