# The "inventory" of hosts to configure.

[remote_vm]
# These are aliases in .ssh/config, instead of specifying details here.
lab066
# lab077

[remote_vm:vars]
# Specify Python interpretter to supress Ansible warning
# about auto-detected Python interpretter.
# Alternatively, you can specify it on each host individually.
ansible_python_interpreter=/usr/bin/python3.9

