- hosts: lab66

  tasks:
    - name: Create Certbot directories
      file:
        path: "/srv/docker/certbot/{{ item.path }}"
        state: directory
        owner: root
        group: root
        mode: "{{ item.mode }}"
      loop:
        - { path: 'conf', mode: '0755' }  # Nginx must traverse this
        - { path: 'www', mode: '0755' }   # Public for Let's Encrypt challenge
      become: yes                 # Required if /srv/docker is owned by root

    - name: Copy Nginx Config and Web Files (synchronize)
      copy:
        src: ../nginx/
        dest: /srv/docker/nginx/
        directory_mode: '0755' 
      become: yes

#   - name: Run Docker Compose
#     community.docker.docker_compose_v2:
#       project_src: /srv/docker/project
#       state: present

